import { ItemRecord } from './types';

export const initialItems: ItemRecord[] = [
  {
    id: 'L001',
    name: 'iPhone 13 Pro',
    type: 'Lost',
    category: 'Electronics',
    description: 'Silver iPhone 13 Pro with a black case. Last seen near the library.',
    location: 'Library',
    date: '2023-10-26T10:00:00Z',
    status: 'Pending',
    itemPictureUrl: 'https://picsum.photos/seed/iphone/200/200',
    ownerDetails: {
      registerNumber: 'RA2111003010101',
      year: 3,
      dept: 'CSE',
    },
  },
  {
    id: 'F001',
    name: 'iPhone 13',
    type: 'Found',
    category: 'Electronics',
    description: 'Found a silver iPhone with a cracked screen protector near the main gate.',
    location: 'Main Gate',
    date: '2023-10-26T12:30:00Z',
    status: 'Pending',
    itemPictureUrl: 'https://picsum.photos/seed/iphonefound/200/200',
  },
  {
    id: 'L002',
    name: 'Dell Laptop Charger',
    type: 'Lost',
    category: 'Electronics',
    description: 'Standard 65W Dell laptop charger.',
    location: 'Tech Park 3rd Floor',
    date: '2023-10-25T15:00:00Z',
    status: 'Claimed',
    itemPictureUrl: 'https://picsum.photos/seed/charger/200/200',
    ownerDetails: {
      registerNumber: 'RA2111003010202',
      year: 2,
      dept: 'ECE',
    },
    handoverDetails: {
      name: 'John Doe',
      faculty: 'Dr. Smith',
      dept: 'ECE',
      cabinNo: 'TP-304',
    },
    matchId: 'F002',
  },
  {
    id: 'F002',
    name: 'Laptop Charger',
    type: 'Found',
    category: 'Electronics',
    description: 'Found a Dell laptop charger in the charging port area.',
    location: 'Tech Park 3rd Floor',
    date: '2023-10-25T16:00:00Z',
    status: 'Returned',
    itemPictureUrl: 'https://picsum.photos/seed/chargerfound/200/200',
    matchId: 'L002',
  },
  {
    id: 'L003',
    name: 'Blue Umbrella',
    type: 'Lost',
    category: 'Accessories',
    description: 'A large blue umbrella with a wooden handle.',
    location: 'Auditorium',
    date: '2023-09-15T11:00:00Z',
    status: 'Pending',
    itemPictureUrl: 'https://picsum.photos/seed/umbrella/200/200',
    ownerDetails: {
      registerNumber: 'RA2111003010303',
      year: 4,
      dept: 'Mechanical',
    },
  },
   {
    id: 'F003',
    name: 'Keys',
    type: 'Found',
    category: 'Personal Items',
    description: 'A set of keys with a red keychain.',
    location: 'Cafeteria',
    date: '2023-11-01T13:00:00Z',
    status: 'Pending',
    itemPictureUrl: 'https://picsum.photos/seed/keys/200/200',
  },
  {
    id: 'L004',
    name: 'Student ID Card',
    type: 'Lost',
    category: 'Personal Items',
    description: 'Lost my ID card, name is Jane Smith.',
    location: 'Main Building',
    date: '2023-11-02T09:00:00Z',
    status: 'Pending',
    itemPictureUrl: 'https://picsum.photos/seed/idcard/200/200',
     ownerDetails: {
      registerNumber: 'RA2111003010404',
      year: 1,
      dept: 'Biotech',
    },
  },
];
